name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  camera: ^0.10.5+3
  camera_elinux:
    path: ../
  flutter:
    sdk: flutter
  path_provider_elinux:
    path: ../../path_provider
  video_player: ^2.4.7
  video_player_elinux:
    path: ../../video_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
