name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  camera: ^0.10.0+1
  camera_elinux:
    path: ../
  flutter:
    sdk: flutter
  path_provider_elinux:
    path: ../../path_provider
  video_player: ^2.4.7
  video_player_elinux:
    path: ../../video_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
